version: 1.0.{build}
skip_tags: true
image: Visual Studio 2019 Preview
configuration: Release
install:
- cmd: git submodule update --init --recursive
before_build:
- cmd: nuget restore
build_script:
- cmd: build.cmd
after_build:
- cmd: >-    
    7z a ShadowsocksR-netcore.zip %APPVEYOR_BUILD_FOLDER%\shadowsocks-csharp\bin\Release\netcoreapp3.0\publish\ShadowsocksR.exe %APPVEYOR_BUILD_FOLDER%\shadowsocks-csharp\bin\Release\netcoreapp3.0\publish\ShadowsocksR.dll %APPVEYOR_BUILD_FOLDER%\shadowsocks-csharp\bin\Release\netcoreapp3.0\publish\ShadowsocksR.runtimeconfig.json
test: off
artifacts:
- path: ShadowsocksR-netcore.zip
  name: ShadowsocksR-netcore.zip