version: 1.0.{build}
skip_tags: true
image: Visual Studio 2019 Preview
configuration: Release
install:
- cmd: git submodule update --init --recursive
before_build:
- cmd: nuget restore
build_script:
- cmd: build.cmd
after_build:
- cmd: >-
    7z a ShadowsocksR-netcore.zip %APPVEYOR_BUILD_FOLDER%\shadowsocks-csharp\bin\Release\netcoreapp3.0\publish\ShadowsocksR.exe %APPVEYOR_BUILD_FOLDER%\shadowsocks-csharp\bin\Release\netcoreapp3.0\publish\ShadowsocksR.dll %APPVEYOR_BUILD_FOLDER%\shadowsocks-csharp\bin\Release\netcoreapp3.0\publish\ShadowsocksR.runtimeconfig.json

    7z a ShadowsocksR-netcore-win32.zip %APPVEYOR_BUILD_FOLDER%\shadowsocks-csharp\bin\Release\netcoreapp3.0\win-x86\publish\ShadowsocksR.exe
    
    7z a ShadowsocksR-net472.zip %APPVEYOR_BUILD_FOLDER%\shadowsocks-csharp\bin\Release\net472\ShadowsocksR.exe

    7z a ShadowsocksR-netcore-win64.zip %APPVEYOR_BUILD_FOLDER%\shadowsocks-csharp\bin\Release\netcoreapp3.0\win-x64\publish\ShadowsocksR.exe
test: off
artifacts:
- path: ShadowsocksR-netcore.zip
  name: ShadowsocksR-netcore.zip
- path: ShadowsocksR-net472.zip
  name: ShadowsocksR-net472.zip
- path: ShadowsocksR-netcore-win32.zip
  name: ShadowsocksR-netcore-win32.zip
- path: ShadowsocksR-netcore-win64.zip
  name: ShadowsocksR-netcore-win64.zip